Secreto31126/whatsapp-api-js

package.json
requests.js
types/contacts.js

I'm scared of merge conflicts, so I will push the bug fix from here :)

Serious bug took priority in this branch

---

package.json
requests.js

This fixes #4 and adds extra functionality.
It's not a bug, it's a feature now 😉

Added statuses updates via POST support

---

package.json
types/contacts.js
types/interactive.js

JSDoc-update

---

README.md
index.js
package.json
types/template.js

ButtonComponent got a rewrite, and now Templates don't need a ButtonComponent for each button, and the indexes aren't asked in the parameters anymore.

ButtonComponent Improvement

---

package.json
types/interactive.js
types/template.js
types/text.js

Improved error's messages, changed wrong error checks (mostly text length errors), and also simplified Template's build proccess code

Thrown errors improvements

---

fetch.js
package.json

node-fetch is now requested ONLY IF fetch isn't defined, so porting to web and other frameworks should be easy peasy :O

Improved fetch usage

---

fetch.js
index.js
package.json
types/text.js

Don't ask me how the reply works, I couldn't make it work, but the request looks EXACTLY like the Postman example, so 🤷‍♂️

Added reply to message and bumped to v14.0

---

README.md
package.json

Took some *inspiration* from https://github.com/tawn33y/whatsapp-cloud-api 😏

Added way more tags

---

.github/workflows/firebase-hosting-merge.yml
.github/workflows/firebase-hosting-pull-request.yml
.github/workflows/github-pages-deploy.yml
.github/workflows/on-pull-request.yml

Imagine having a dream telling you how to fix this...

Actions fix

---

src/fetch.js
src/index.js
test/index.test.js

Added phone_number_id check for media calls

---

package.json

I can't believe I forgot it again

Increased version number

---

src/index.js

Fixed the example codes

---

.gitignore
src/index.js
test/index.test.js

Hello,
It's just my suggestion, how it can be.
```javascript
// Read Running outside of Nodejs to see support for other engines
const { WhatsAppAPI, Handlers, Types } = require("whatsapp-api-js");
const { Text, Media, Contacts } = Types;
const Token = "YOUR_TOKEN";
const AppSecret = "YOUR_APP_SECRET";
const WebhookVerifyToken = "YOUR_WEBHOOK_VERIFY_TOKEN";
const Whatsapp = new WhatsAppAPI(Token, AppSecret, WebhookVerifyToken);
// Assuming post is called on a POST request to your server
function post(e) {
// The Handlers work with any middleware, as long as you pass the correct data
return Whatsapp.post(e);
}
Whatsapp.on("message", async (phoneID, phone, message, name, raw_data) => {
console.log(`User ${phone} (${name}) sent to bot ${phoneID} ${JSON.stringify(message)}`);
let promise;
if …
```

Implement EventEmitter for WhatsAppAPI, add webhook validation

---

src/messages/interactive.js

The API error was really unintuitive and the endpoint had really strange interactions, as documented in #1. I hope this new checks prevents future issues.
Closes #54

Updated Interactive's Header checks

---

src/index.ts
src/messages/contacts.ts
src/messages/interactive.ts
src/messages/location.ts
src/messages/media.ts
src/messages/reaction.ts
src/messages/template.ts
src/messages/text.ts

It used to make sense with JSCheck, but since the code was rewritten in TS, there's no longer the need to check if a variable was provided or similar cases.
This change actually improves what #69 couldn't, which was allowing the user take more control over the components and the messages. Before it would throw errors if the user tried playing around with the variables, but now a simple `// @ ts-ignore` will allow the creativity flow.
I'm quite happy with this changes, simplified by a lot the code complexity.

Removed most of the checks

---

.github/workflows/npm-deploy.yml

Much easier, crypto.subtle should exists in 18 for sure

Bumped npm-deploy.yml Node env to 18

---

src/messages/interactive.ts
src/messages/template.ts
src/types.d.ts
typedoc.json

Templates deep rewrite

---

package.json
src/index.ts

There were a few TS signatures issues

Signature fix

---

src/index.ts

Fixed markAsRead bug

---

src/index.ts
test/index.test.cjs

Finally brought back the unit tests I commented some months ago...
Didn't backfire at all (cof #119 cof)
Also took the oportunity to delete legacy unit tests. They will absolutely not backfire this time (I hope 😄)

Tests updates

---

package.json
src/emitters.d.ts
src/types.d.ts
tsconfig.json

Who would have guessed that you need to use TypeScript to replicate a TypeScript issue?
Fixed some missing extensions
Fixed missing dependecy types (closes #121)
Fixed TS2307 (closes #113)

TS issues fixs

---

BREAKING.md
README.md

I'm happy with it, easy to follow and straight to the point.
I hope I didn't miss any big change...

Breaking changes list

---

src/index.ts

Moved duplicated code into a generic function (I bet Java can't do this :)

Dedup code

---

src/messages/text.ts

This should trigger an alpha release

Minor TSDoc fix

---

src/types.d.ts

Still trying to test alpha releases

Updated rant

---

src/index.ts

I can finally close #114 and consider the verification process stable and done.
Thanks to everyone who worked on the code and commented on the issues!

Signature Verification "bug fix"

---

src/index.ts
test/index.test.cjs

Copilot X could auto complete this, I'm too lazy to explain the PR :)
Closes #141

Broadcast Message

---

src/index.ts

Forgot to push before the merge :/

TS Doc improvement

---

src/messages/index.ts
src/setup/index.ts

Just learnt this trick

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Improved contributiors experience
Closes #152

Contributing documentation

---

EXAMPLES/README.md
EXAMPLES/contacts.md
EXAMPLES/interactive.md
EXAMPLES/location.md
EXAMPLES/main.md
EXAMPLES/media.md
EXAMPLES/reaction.md
EXAMPLES/template.md
EXAMPLES/text.md
README.md

Closes #156
Make it easier to get started with the library by including code examples for most message types

Added EXAMPLES

---

package.json
src/messages/contacts.ts
src/messages/template.ts

Seems like enumerable: true was missing
Unit tests would have found this early...

Bug fix for defineProperty

---

EXAMPLES/README.md
EXAMPLES/template.md
src/messages/template.ts

OTP prefab

---

src/index.ts

- [] It's really useful if your PR references an issue where it is discussed ahead of time.
- [] This message body should clearly illustrate what problems it solves.
- [] Ideally, include a test that fails without this PR but passes with it.
- [] Run the tests with `npm run test` and lint the project with `npm run lint` and `npm run prettier`

Removed extra enter

---

README.md

Fixed get() example in README

---

README.md
src/emitters.d.ts

fix: allow event handlers to be asynchronous

---

src/middleware/express.ts
src/utils.ts

Simplify the handlers' usage for Express

Express middleware

---

EXAMPLES/template.md
src/messages/template.ts

I actually like the new code over the previous iteration, it feels closer to the APIs wording and structure (each button is a component). It unfortunately looses some local checks such as no more than 3 payload buttons, but since those limits seems quite customizable for WhatsApp, I prefer leaving them as is.
Closes #208

Template update

---

EXAMPLES/main.md
package-lock.json
package.json
src/middleware/adonis.ts
src/middleware/core.ts
src/middleware/express.ts
src/middleware/globals.ts
src/middleware/index.ts
typedoc.json

Finished implementing the most requested frameworks' middlewares. It was a mess, but it works, so Idc.

Native middleware

---

.all-contributorsrc
README.md
package-lock.json
package.json

Add contributors table

---

.github/workflows/npm-deploy.yml

Stop testing against Node 16

---

ENVIRONMENTS.md
EXAMPLES/README.md
README.md
src/messages/contacts.ts
src/messages/index.ts
src/messages/interactive.ts
src/messages/location.ts
src/messages/media.ts
src/messages/reaction.ts
src/messages/template.ts
src/messages/text.ts
src/middleware/globals.ts
src/middleware/index.ts
src/setup/index.ts
src/types.ts

Docs update

---

BREAKING.md
src/messages/globals.ts
src/messages/interactive.ts
src/types.ts

Last moves

---

EXAMPLES/README.md
EXAMPLES/template.md
package.json
src/messages/template.ts

Carousel Template support

---

src/index.ts
src/types.ts
test/index.test.cjs

They seriously didn't have enough with making a new feature, so they also increased their API version ONE DAY after the breaking update...

Version API bump

---

.github/workflows/firebase-hosting-pull-request.yml
.github/workflows/npm-deploy.yml
.github/workflows/on-pull-request.yml
.github/workflows/web-release.yml

They are doomed for a full rewrite

Minor changes

---

.github/workflows/on-pull-request.yml

This changes are meant to improve the actions' triggers and performance. They are a mess, some time in the future they will be rewritten.

Updated actions

---

build.js
package.json
src/standalone.ts
tsconfig.json

Started as a GAS compatibility restore and finished reducing the build size by 2mb.

Build improvements

---

ENVIRONMENTS.md
README.md
package.json

GAS support

---

src/messages/interactive.ts

Improve interactive's documentation

---

src/index.ts

Update error message

---

src/types.ts

API types QoL

---

src/types.ts

Especially if the documentation is written by Facebook

Never trust the official documentation

---

EXAMPLES/README.md
EXAMPLES/template.md
src/messages/template.ts

Added Limited-Time Offer component

---

src/emitters.ts
src/index.ts

Waaaaay cleaner than I expected. I'm not going to unit test it :)

Show yourself

---

src/messages/interactive.ts
src/types.ts

I still haven't tested #169 with this new knowledge, we might finally find out what a MAGICAL_INTERACTIVE or whatever is called is 😄

Added interactive CTA support

---

src/messages/template.ts
src/utils.ts

Flow template

---

EXAMPLES/interactive.md
EXAMPLES/template.md

Examples updated

---

package-lock.json
package.json
src/emitters.ts
src/index.ts
src/middleware/bun.ts
src/middleware/deno.ts
src/middleware/sveltekit.ts
src/middleware/web-standard.ts
src/setup/node.ts
src/types.ts
tsconfig.json

Finally...
~Finally, Undici has a separate package for the types, making the package size waaaay smaller.~
Nvm, I forgot I use it for unit testing, my bad
Closes #261

Undici Types

---

.github/workflows/alpha-release.yml
.github/workflows/npm-deploy.yml
.github/workflows/web-release.yml

Reverts Secreto31126/whatsapp-api-js#275

Revert "chore(deps): actions/upload-artifact action v4"

---

.github/workflows/alpha-release.yml
.github/workflows/npm-deploy.yml
.github/workflows/web-release.yml

Reverts Secreto31126/whatsapp-api-js#274

Revert "chore(deps): actions/download-artifact action v4"

---

EXAMPLES/interactive.md
package.json
src/messages/interactive.ts
src/types.ts

Interactive location

---

package.json
src/types.ts

Added request_welcome type

---

BREAKING.md
package.json
src/emitters.ts
src/index.ts
src/types.ts

Doc update

---

package.json
src/index.ts
src/types.ts
test/index.test.cjs

Version update

---

package.json

A new beginning

---

.prettierignore
src/messages/globals.ts
src/messages/interactive.ts

Interactive breaking update

---

src/messages/template.ts
src/types.ts

Added TemplateComponent interface

---

src/index.ts
test/index.test.cjs

fix: typo _authenicatedRequest

---

src/index.ts
test/index.test.cjs

Removed multipart header for uploadMedia method

---

src/index.ts

Rather than waiting within the function to send the messages, immediately return an array of timeout promises which will execute the sendMessage
Rather than waiting within the function to send the messages, immediately return an array of timeout promises which will execute the sendMessage.

Improved broadcastMessage

---

src/types.ts

Bump API version to v20.0

---

BREAKING.md
ENVIRONMENTS.md
EXAMPLES/README.md
EXAMPLES/main.md
README.md
src/emitters.ts
src/index.ts
tsdoc.json

v4 Documentation

---

src/emitters.ts
src/index.ts
src/utils.ts

Tested and fixed in Secreto31126/whatsapp-api-test

Emitters fix

---

.github/workflows/alpha-release.yml
.github/workflows/npm-deploy.yml
.github/workflows/on-pull-request.yml

Added provenance checks, updated to Node 20, and test agains Node 22

Actions Update

---

src/middleware/index.ts
src/middleware/next.ts
src/middleware/web-standard.ts

Added NextJS App Router middleware

---

package.json
src/index.ts
src/messages/contacts.ts
src/messages/template.ts
src/middleware/adonis.ts
src/middleware/bun.ts
src/middleware/deno.ts
src/middleware/express.ts
src/middleware/next.ts
src/middleware/node-http.ts
src/middleware/sveltekit.ts
src/middleware/vercel.ts
src/middleware/web-standard.ts
src/types.ts

Giving some love to the types.
Closes #366 (Hopefully)

Improved types

---

EXAMPLES/interactive.md
src/messages/globals.ts
src/messages/interactive.ts

Product rework

---

EXAMPLES/README.md
EXAMPLES/template.md
src/messages/globals.ts
src/messages/template.ts

Single Product Message support

---

build.js
package.json
test/index.test.js
tsconfig.json

As mentioned in #385, CJS native support won't be offered any longer. Maintaining the code was painfully hard, so this will remove lots of compatibility issues.

Remove CJS native support

---

package-lock.json
package.json
src/middleware/azure.ts

Azure Functions Middleware

---

package.json
src/emitters.ts
src/index.ts
src/types.ts
test/index.test.js

Added typing indicators

---

src/types.ts

API version bump

---

src/emitters.ts
src/index.ts
src/types.ts
test/index.test.js

I hated it, it was annoying and didn't help at all.

Remove parsed option

---

EXAMPLES/README.md
EXAMPLES/interactive.md
EXAMPLES/main.md
package.json
src/emitters.ts
src/index.ts
src/messages/interactive.ts
src/types.ts

As mentioned in #432, this update will add Calls API support to the library, including API methods and webhooks.
Things missing:

Calls support

---

src/messages/template.ts

Make TapTargetComponent constructor similar to ActionCTA signature

---

EXAMPLES/README.md
EXAMPLES/template.md
src/messages/template.ts
src/types.ts

I actually think this is great! If only they had created an entry in their changelog when it was added, I would have updated the library on the spot.

Add parameter_name support

---

package.json
src/apis/block.ts
src/apis/call.ts
src/apis/index.ts
src/apis/media.ts
src/apis/message.ts
src/apis/qr.ts
src/apis/webhook.ts
src/emitters.ts
src/index.ts
src/messages/interactive.ts
typedoc.json

Following Java's style, the library now uses multiple interfaces with all the documentation to define the behaviors in a more orderly manner. The index.ts file went from 1500 lines to just under 1000.
So much cleaner and easy to edit 😄.

DX QoL with modular documentation
