README.md
src/index.ts
test/index.test.cjs

No one said it would be pretty, although I like it more than on("string", ...) syntax.
The only lost feature is multi callbacks support, which could have been a nice feature, but not really the intended way to use the library.
However, I think this provides an aditional type check for the callbacks to match the valid arguments.

Server agnostic recreation of EventsEmmiter

---

.github/dependabot.yml
.github/renovate.json
package-lock.json
package.json

Renovatebot is a much more advanced dependency management tool, available as [open source][renovatebot]. It supports a wide range of configuration options.
The configuration is pretty vanilla with the exception of customizing the PR body to remove the header banner. I've set it to check weekly, but you can toggle runs with the dashboard.
[renovatebot]: https://github.com/renovatebot/renovate
I installed / enabled it on my fork of this repo for demo purposes: https://github.com/jbergstroem/whatsapp-api-js
- Dependency dashboard (tells you whats new, allows you to start another check): https://github.com/jbergstroem/whatsapp-api-js/issues/1
- Example grouped PR that I triggered from Dashboard (which otherwise would've occured on Monday morning)): …

chore: replace dependabot with renovatebot

---

package-lock.json
package.json

C8 uses the v8 built-in coverage tool in Node.js. This means faster coverage reports as well as a smaller `node_modules` folder (163M -> 146M)
Also, introduce a (humble) engine requirement of Node.js 10.10, which is when the v8 coverage tool was introduced.

feat: replace nyc with c8

---

.gitignore
lib/common/package.json
package.json

Rather than keeping the package.json, write it on build time

CommonJS build process improve

---

src/messages/interactive.ts
src/messages/template.ts
src/messages/text.ts

Text was never meant to be used in other objects, but the docs used to say text were a Text object.
Now they updated most of the types of text to string, so it's safe to just ask for a string in our classes too.

Removed use of internal Text

---

src/index.ts
src/setup/bun.ts
src/setup/deno.ts
src/setup/index.ts
src/setup/node.ts
src/setup/web.ts
src/types.d.ts
tsdoc.json
typedoc.json

This should help preventing #114 point 2 from happening, as the end user won't need to configure the ponyfills manually

Quick Setup for most enviroments

---

src/messages/contacts.ts
src/messages/interactive.ts
src/messages/template.ts
src/types.d.ts

I thought making some types less generic would be good to support future updates and let the final user customize everything, but the fact that ts-ignore exists turns all of it pointless.
Plus, ClientMessageComponent was used really inconsistent, so I'm happy to remove it.

Going for less _generic_ types

---

build.js
package.json
tsconfig.json

Lesson learnt: exports property is for TS, and typesVersions is for VS Code IntelliSense for JS.
Also, if possible, avoid at all cost using * in any of them, as it will most likely fail catastrophically.
Fixes the main import needing /index (I hope) (#157)

Exports fix

---

package.json
src/messages/template.ts

Closes #175
Sending templates with phone numbers is broken on the API, as they capture variables even though they don't take any...

Fixed template's parameters

---

package.json

This will alleviate the 2mb package size :)

Allow tree shaking

---

ENVIRONMENTS.md
README.md
package.json
src/emitters.ts
src/index.ts
test/index.test.cjs

Who doesn't hate code repetition? The new `reply` method aims at not only saving 20/30 chars per message, but also allow code splitting without needing to create another WhatsAppAPI instance.

Added reply method to OnMessage callback

---

package.json
src/messages/index.ts
src/messages/location.ts
src/messages/reaction.ts
src/messages/text.ts
test/index.test.cjs

Improve CJS code experience

---

src/types.ts

This PR adds the type definition for an interactive nfp_reply message. This message is received when sharing an address, or completing an flow.

Add Native Flow Response reply type definition

---

src/index.ts
src/utils.ts
test/index.test.cjs

Handle Unicode characters

---

package.json
src/index.ts
src/types.ts
test/index.test.cjs

Implemented user_function to handle callbacks

---

src/index.ts
src/types.ts
test/index.test.cjs

Added version pinning recommendation

---

package.json
src/index.ts
test/index.test.cjs

Fixed fetchMedia method by using a custom User-Agent as discussed in #335. Even though I still don't know why it works, I doubt we will ever figure it out.

Fetch media fix

---

package.json
src/emitters.ts
src/index.ts
src/types.ts

Based on #325, I decided to implement the requested changes with a different perspective.
The `message_status` property is still missing from my tests to the API, so I decided to implement it as an optional, and rather than asumming success, use it to indicate the user that the message is `held_for_quality_assessment` if the value says so.
On the other hand, the `timestamp` argument was added to the OnStatus emitter, which was not able to …

Emitters update

---

src/emitters.ts
src/index.ts
src/middleware/adonis.ts
src/middleware/express.ts
src/middleware/globals.ts
src/middleware/node-http.ts
src/middleware/web-standard.ts
src/types.ts
test/index.test.cjs

https://github.com/Secreto31126/whatsapp-api-js/issues/335#issuecomment-2103905066
Now it's possible to return custom data from the OnMessage and OnStatus events, which will be the post() return value.

Allow emitters to return custom data

---

package-lock.json
test/index.test.cjs
test/webhooks.mocks.cjs

Fixes and audits

---

src/emitters.ts
src/index.ts

Emitters QoL fixes

---

src/index.ts

As commented by @tecoad on #335
https://github.com/Secreto31126/whatsapp-api-js/issues/335#issuecomment-2105458688
Closes #335 (again :)

Modularized request validation

---

src/index.ts
test/index.test.cjs

I want to fix the verifyRequestSignature method inside `index.ts` file. From the jsdoc docs,  the returnred boolean value should indicate that the signature is valid. Hope it helps! :) 
-   [-] Ideally, include a test that fails without this PR but passes with it.
-   [-] Run the tests with `npm run test` and lint the project with `npm run lint` and `npm run prettier`

Fix verify signature double negation

---

EXAMPLES/README.md
EXAMPLES/template.md
src/messages/template.ts

Product carousel support

---

src/index.ts
src/messages/contacts.ts
src/types.ts
test/index.test.js

With this new structure, ClientMessageRequest is fully typed and will probably be faster to send messages as JSON.stringify is called less times.
Closes #374

Removed nested message stringify

---

src/index.ts
src/types.ts

Improved ClientMessageRequest typing

---

ENVIRONMENTS.md
package.json
src/errors.ts
src/index.ts
src/middleware/adonis.ts
src/middleware/express.ts
src/middleware/node-http.ts
src/middleware/vercel.ts
src/middleware/web-standard.ts
src/types.ts
src/utils.ts
test/index.test.js
typedoc.json

These new classes allow differentiating between user's bugs and library ones, so the external throws are no longer retained by the webhook handlers and helps the developers to better detect and fix their ~bad~ code issues :)
This could also work as an alternative to setting the emitters' return type, as it's now possible to throw whatever you want. Anyway, I think I will preserve the current system as it provides type safety return values rather than unknown from try catch.

Library error classes

---

src/errors.ts
src/index.ts
src/middleware/express.ts

Docs improvements

---

src/emitters.ts
src/errors.ts
src/index.ts
src/messages/contacts.ts
src/messages/globals.ts
src/messages/interactive.ts
src/messages/template.ts
src/middleware/adonis.ts
src/middleware/express.ts
src/middleware/node-http.ts
src/middleware/vercel.ts
src/middleware/web-standard.ts
src/setup/bun.ts
src/setup/deno.ts
src/setup/node.ts
src/setup/web.ts
src/types.ts

As recommended in #376, I tested the library with https://arethetypeswrong.github.io/, and adding the .d.ts file extensions makes the 🥴 go away, so yeah, I think this is a keeper.

Added .d.ts extension to import type

---

package.json

Node can require modules, but needs the exports to define them explicitly.
Closes #408

Restore cjs "support"

---

.github/workflows/npm-deploy.yml
.github/workflows/on-pull-request.yml
ENVIRONMENTS.md
src/setup/node.ts

I kinda hated v18 tho, undici was in a weird state and crypto.subtle wasn't globally available yet.

Drop Node v18 support
